Name - Pritiparna panigrahy,
Branch- IT, TASK-3


In [7]:
import numpy as np


1D array operation:

In [8]:
arr=np.array([22,33,1,5,89])

In [10]:
np.sum(arr)

np.int64(150)

In [11]:
np.mean(arr)

np.float64(30.0)

In [12]:
np.min(arr)

np.int64(1)

In [13]:
np.max(arr)

np.int64(89)

In [14]:
np.sort(arr)

array([ 1,  5, 22, 33, 89])

In [16]:
arr.size

5

In [17]:
arr.dtype

dtype('int64')

In [28]:
arr.ndim

1

multi-dimension array operation:

In [19]:
np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [27]:
np.linspace(4,50,9)

array([ 4.  ,  9.75, 15.5 , 21.25, 27.  , 32.75, 38.5 , 44.25, 50.  ])

In [34]:
arr_md=np.array([[1,4,6],[5,23,7],[5,1,2],[6,91,87]])

In [35]:
arr_md.ndim

2

In [44]:
priti=arr_md.reshape(4,3)

In [39]:
priti

array([[ 1,  4,  6],
       [ 5, 23,  7],
       [ 5,  1,  2],
       [ 6, 91, 87]])

In [40]:
priti.shape

(4, 3)

In [49]:
np.sum(priti,axis=1)

array([ 11,  35,   8, 184])

In [54]:
f=priti.flatten()

Slicing:

In [55]:
f[:5]

array([ 1,  4,  6,  5, 23])

In [57]:
f[5:]

array([ 7,  5,  1,  2,  6, 91, 87])

In [58]:
f[2:5]

array([ 6,  5, 23])

In [59]:
a=f

In [64]:
a[3]=100

In [65]:
a


array([  1,   4,   6, 100,  23,   7,   5,   1,   2,   6,  91,  87])

In [66]:
f

array([  1,   4,   6, 100,  23,   7,   5,   1,   2,   6,  91,  87])